name: Build & Push Docker Image

on:   
  push:
    branches: 
      - master

env:
  NAME: liatrio/gitty-up

jobs:
  docker:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build and push the Docker image
      run: |
        export VERSION=$(git describe --tags)
        docker build . --file Dockerfile --tag $NAME:$VERSION
        docker login --username ${{ secrets.DockerHubUsername  }} --password ${{ secrets.DockerHubPassword }}
        docker push $NAME:latest
        docker push $NAME:$VERSION